### ISSUE TITLE
Merge with atom-lebab

### ISSUE THREAD

**Issue by nene** [jaunkst/atom-lebab-convert#3]
I discovered that there are two Lebab packages for Atom: this one, and [atom-lebab](https://github.com/ga2mer/atom-lebab).

Although `atom-lebab` has only had one `0.1` release its implementation looks superior to me because instead of asking you to first install Lebab with npm and executing it via shell it's specifying Lebab as a dependency in its package.json and using JavaScript API to invoke it.

With the release of Lebab 2.0 the command line API has changed, so `atom-lebab-convert` is now effectively broken. Therefore this might be a good point in time to consider the further destiny of this project: whether to spend time upgrading it or to abandon it altogether.

I'm not sure whether there's actually any code to merge into `atom-lebab`. I think it's more beneficial to merge the knowledge of developers. For example `atom-lebab-conver` has some configuration while `atom-lebab` has none.

A major benefit of merging these projects would be to eliminate the confusion when one searches for Lebab package in Atom and is forced to choose between two competing implementations.

**Comment by jaunkst** [comment]
I think it should look for a local lebab node_module in the project, and then fallback to a global install of lebab if it is not found. 

I suppose if neither is found that it could use an internal lebab dependency via its own package.json

**Comment by jaunkst** [comment]
I will update this module to working with the new command line API and enable fallbacks, and add new options.

**Comment by jaunkst** [comment]
https://github.com/jaunkst/atom-lebab-convert/issues/5
